CREATE TABLE CLIENTES (
	ID_Cliente VARCHAR2(30) CONSTRAINT PK_ID_CLIENTE PRIMARY KEY,
	Nombre VARCHAR2(30),
	Tarjeta_bancaria NUMBER(19,0),
	Telefono VARCHAR2(15),
	Mail VARCHAR2(50)
);

CREATE TABLE COCINEROS (
	ID_Cocinero VARCHAR2(30) CONSTRAINT PK_ID_COCINERO PRIMARY KEY,
	Nombre VARCHAR2(30),
	Apellidos VARCHAR2(30),
	DNI VARCHAR2 (9),	
	Fe_nacimiento VARCHAR2(30)
);

CREATE TABLE REPARTIDORES (
	ID_Repartidor VARCHAR2(30) CONSTRAINT PK_ID_REPARTIDOR PRIMARY KEY,
	Nombre VARCHAR2(30),
	Apellidos VARCHAR2(30),
	Telefono VARCHAR2(15),
	DNI VARCHAR2 (9),
	Fe_nacimiento VARCHAR2(30)
);

CREATE TABLE PEDIDOS (
	Numero_pedido NUMBER(9,0) CONSTRAINT PK_NUMERO_PEDIDO PRIMARY KEY,
	Precio NUMBER(5,2),
	Hora VARCHAR2(6),
	Fecha VARCHAR2(30),
	ID_Cliente VARCHAR2(30) CONSTRAINT FK_ID_CLIENTE_PEDIDOS REFERENCES CLIENTES(ID_Cliente),
	ID_Repartidor VARCHAR2(30) CONSTRAINT FK_ID_REPARTIDOR_PEDIDOS REFERENCES REPARTIDORES(ID_Repartidor)
);

CREATE TABLE PREPARAN (
	ID_Cocinero VARCHAR2(30) CONSTRAINT FK_ID_COCINERO_PREPARAN REFERENCES COCINEROS(ID_Cocinero),
	Numero_Pedido NUMBER(9,0) CONSTRAINT FK_NUMERO_PEDIDO_PREPARAN REFERENCES PEDIDOS(Numero_Pedido)
	
);
